# Generated by Django 5.0.6 on 2024-05-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_person_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
