# Generated by Django 5.0.6 on 2024-05-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
