# Generated by Django 5.0.6 on 2024-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_rename_user_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='social/images/default.jpg', upload_to='social/images'),
        ),
    ]
