# Generated by Django 5.0.6 on 2024-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='social/images/default.png', upload_to='social/images'),
        ),
    ]
