# Generated by Django 5.0.6 on 2024-06-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_comment_post_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_by', through='social.Like', to='social.post'),
        ),
    ]
