# Generated by Django 5.0.6 on 2024-05-30 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='item',
            field=models.FileField(default='', upload_to='music/songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
            preserve_default=False,
        ),
    ]
