# Generated by Django 5.0.6 on 2024-05-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_playlistitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
